experimentTypes: # keys are from enums
  - name: Canary
    handlers:
      start: start
      rollback: finish
      finish: finish
      failure: finish
  - name: A/B
    handlers:
      start: start
      rollback: finish
      finish: finish
      failure: finish
  - name: Performance
    handlers:
      start: start
  - name: BlueGreen
    handlers:
      start: start
      rollback: finish
      finish: finish
      failure: finish
metrics:
  requestCount: request-count
